### PR TITLE
Prepare for Melpa

### PR DESCRIPTION
**Pull request by lassik**

### CODE REVIEW

**Comment by lassik** [comment]
If you merge these, I'll send them the PR to add the package.

This PR addresses:

* The changes requested in https://github.com/melpa/melpa/pull/5816
* checkdoc warnings
* package-lint warnings
* byte-compile-file warnings

**Comment by lassik** [comment]
@jgarte Can you give this a quick thumbs up/down when you have the time? It's all simple maintenance, apart from disabling the hook which MELPA asked for.

**Comment by jgarte** [comment]
> If you merge these, I'll send them the PR to add the package.
> 
> This PR addresses:
> 
>     * The changes requested in [Create mint-mode melpa/melpa#5816](https://github.com/melpa/melpa/pull/5816)
> 
>     * checkdoc warnings
> 
>     * package-lint warnings
> 
>     * byte-compile-file warnings

@lassik Thanks for the contribution. Sorry for the delay. I merged your changes. Feel free to add the package to MELPA. That would be much appreciated. 

I also made a release for 1.0.3 and sent a package update to GNU Guix: https://issues.guix.gnu.org/57729

**Comment by jgarte** [comment]
@lassik Would you like commit access to this repo to help with maintenance?

**Comment by lassik** [comment]
@jgarte Thanks for the offer but I don't really use Mint. It's better if people who do maintain the Emacs package.

**Comment by lassik** [comment]
@creatorrr @gdotdesign @jgarte This repo seems like the most complete Emacs package for Mint. Would you be willing to move it under the https://github.com/mint-lang organization?

**Comment by jgarte** [comment]
@lassik Not sure if that really is necessary since IIRC, most of the developers in that organization who have commit access are not using emacs but vscode and `emacs-mint-mode` is already mentioned here:

https://mint-lang.com/guide/getting-started/tools

There's a vim mode mentioned in that link that is also not part of the mint organizations GitHub account and developed in their own forge space.

**Pull request merged**
